---
- name: Ansible
  hosts: localhost
  become: true
  gather_facts: no
  tasks:
    - name: vault-decrypt
      shell: "ansible-vault decrypt /var/lib/jenkins/workspace/terraform-test/key.json --vault-password-file pass --output key2.json"
      ignore_errors: True
